---
- name: Adding MongoDB Repo Key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "9DA31620334BD75D9DCB49F368818C72E52529D4"
    state: "present"

- name: Adding MongoDB Apt Repo
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse"
    state: "present"

- name: Installing MongoDB
  apt:
    name: "mongodb-org"
    state: "present"

- name: Enabling and Starting MongoDB Service
  service:
    name: "mongod"
    state: "started"
    enabled: yes

- name: config | Configuring MongoDB
  template:
    src: "templates/mongod.conf.j2"
    dest: "/etc/mongod.conf"
  register: "mongodb_configured"
  notify: "Restart MongoDB"

- name: creating mongod users
  mongodb_user:
    database: nodetodo
    name: testuser
    password: 12345
    state: present
